#constants

# ANSI escape codes for some colors
RED = '\033[31m'  # Red text
GREEN = '\033[32m'  # Green text
YELLOW = '\033[33m'  # Yellow text
BLUE = '\033[34m'  # Blue text
MAGENTA = '\033[35m'  # Magenta text
CYAN = '\033[36m'  # Cyan text
RESET = '\033[0m'  # Reset to default color

#STATE MACHINE
ONE_HOUR_1ST_DATA = 1
ONE_HOUR_2ND_DATA = 2
ONE_HOUR_3RD_DATA = 3
TEN_MINUTES_DATA = 4

#COMMANDS
SIMPLE_ACK = 1
DO_MEASUREMENT_IMMEDIATELY = 2
DO_MEASUREMENT_AFTER_10_MINUTES = 3
DO_MEASUREMENT_AFTER_1_HOUR = 4
DO_MEASUREMENT_AFTER_3_HOURS = 5
DO_MEASUREMENT_AFTER_9_HOURS = 6


#LIMITS
HOARFROST_CURRENT_DANGER_LIMIT = 0.10
HOARFROST_PREDICTED_DANGER_AVG_LIMIT = 0.05
HOARFROST_PREDICTED_DANGER_MAX_LIMIT = 0.08

