#constants

#STATE MACHINE
ONE_HOUR_1ST_DATA = 1
ONE_HOUR_2ND_DATA = 2
ONE_HOUR_3RD_DATA = 3
TEN_MINUTES_DATA = 4

#COMMANDS
SIMPLE_ACK = 1
DO_MEASUREMENT_IMMEDIATELY = 2
DO_MEASUREMENT_AFTER_10_MINUTES = 3
DO_MEASUREMENT_AFTER_1_HOUR = 4
DO_MEASUREMENT_AFTER_3_HOURS = 5
DO_MEASUREMENT_AFTER_9_HOURS = 6


#LIMITS
HOARFROST_CURRENT_DANGER_LIMIT = 0.20
HOARFROST_PREDICTED_DANGER_AVG_LIMIT = 0.10
HOARFROST_PREDICTED_DANGER_MAX_LIMIT = 0.15

